### ISSUE TITLE
A question about SDF in the paper.

### ISSUE THREAD

**Issue by KeKer7** [wen-yuan-zhang/GS-Pull#2]
What an enlightening paper! I happened to be trying a 'pull' approach as well. 
I have a question: Does the SDF network undergo separate training? How is the position of the query q determined?

**Comment by wen-yuan-zhang** [comment]
Thanks for your attention! The SDF network indeed needs separate training besides 3D Gaussians. The query q is sampled around each gaussians following a normal disitribution with a pre-calculated standard value. The details of the sampling strategy can be found in [Neural-Pull](https://github.com/mabaorui/NeuralPull).

**Comment by KeKer7** [comment]
Thank you for your reply!
